ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.cashregister.ApplicationKt.module ]
    }
}

database {
    url = "jdbc:postgresql://localhost:5432/cashregister"
    url = ${?DATABASE_URL}
    user = "postgres"
    user = ${?DATABASE_USER}
    password = "postgres"
    password = ${?DATABASE_PASSWORD}
    driver = "org.postgresql.Driver"
}
